# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mohammad Haghighipoor
subtitle: Innovative Software Developer & Problem Solver
# avatar_url: https://avatars.githubusercontent.com/u/16705068?v=4
avatar_url: /assets/images/ohamhpr.jpg
description: Explore Mohammad Haghighipoor's portfolio and projects. A software developer dedicated to innovation and impactful solutions.
keywords: Mohammad Haghighipoor, Mohammad Haghighi poor, software developer, innovation, innovative solutions, portfolio, problem solving


email: mohammad.haghighi.poor@gmail.com
descriptionIGNORED: >- # this means to ignore newlines until "baseurl:"
  The day doesn't run me; I run the day,
  I make sure every single day has a clear and well-communicated structure.
  It also means changes are welcome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohamhpr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

youtube_username: mohammadhaghighipoor3044
linkedin_username:  ohamhpr
github_username:  ohamhpr
twitter_username: ohamhpr
stack_overflow_username:  ohamhpr
instagram_username:  ohamhpr

under_construction_message: Thank you for your interest!<br/>
  I'm making some improvements and will have everything ready soon.

# Build settings
# theme: minima
plugins:
  - jekyll-feed

collections:
  ideas:
    output: true
  projects:
    output: true
  experiences:
    output: true
  challenges:
    output: true

defaults:
  - scope:
      path: ""
      type: "ideas"
    values:
      layout: project
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: single
  - scope:
      path: ""
      type: "challenges"
    values:
      layout: single
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

docsOrder:
    - _projects/rt_dispatch.md
    - _projects/order_delivery.md
    - _ideas/neoterra-cities.html
    - _projects/shop_floor_meeting.html
    - _projects/limousine_reservation.html
    - _projects/driver_assistance_center.html
    - _projects/equipment_management_system.html
    - _projects/paybank_android_app.html
    - _projects/push_notification.html
    - _projects/sensors_mgm.html
    - _ideas/smart-city.md
    - _projects/enterprise_pop3_mail_server.html
    - _projects/workflow_engine.html
    - _projects/douran_bi.html
    - _projects/selak_dentistry_clinic.html
    - _projects/network_listener.md
    - _projects/course_selection_kiosk.md
    - _projects/concrete_curbing_machine.html
    - _projects/shadman_acc.html
    - _projects/sepam.html
    - _projects/emamali_labrtor.html
    - _projects/ivr.html
    - _ideas/ecity.html
    - _experiences/fidasys.md
    - _experiences/resertrac.html
    - _experiences/nrdc.html
    - _experiences/tva.html
    - _experiences/douran.html
    - _experiences/selakteb.html
    - _experiences/kankash.html
    - _experiences/self_emp.html
    - _challenges/gps_drift.md
    - _challenges/cross_app_display.md